/*
 * File: app/view/mainView.js
 *
 * This file was generated by Sencha Architect version 3.0.1.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyInyungu.view.mainView', {
    extend: 'Ext.tab.Panel',

    requires: [
        'Ext.dataview.List',
        'Ext.XTemplate',
        'Ext.Panel',
        'Ext.tab.Bar',
        'Ext.Button'
    ],

    config: {
        fullscreen: true,
        id: 'mainView',
        items: [
            {
                xtype: 'container',
                title: 'Products',
                iconCls: 'info',
                layout: 'card',
                items: [
                    {
                        xtype: 'list',
                        itemId: 'mylist',
                        itemTpl: [
                            '<div>{productname}</div>',
                            '<div><span style=\'font-size:9px\'><p>Murayisanga mu karere ka {district} ku giciro {currentprice}<p/></span></div>'
                        ],
                        store: 'Inyungus'
                    },
                    {
                        xtype: 'panel',
                        tpl: [
                            '<div>id :{id}</div>',
                            '<div class="inyunguProductame">Igihingwa :{productname}</div>',
                            '<div class="taskName">Igiciro :{currentprice}</div>',
                            '<div class="taskName">Ingano :{quantity}</div>',
                            '<div class="taskName">Ingiro :{mesure}</div>',
                            '<div>Igiciro cyose :{totalamount}</div>',
                            '<div>Amazina :{firstname}</div>',
                            '<div>Intara :{province}</div>',
                            '<div>Akarere :{district}</div>',
                            '<div>Akagali :{akagali}</div>',
                            '<div>Umudugudu :{umudugudu}</div>',
                            '<div>Telephoni :{telephone}</div>',
                            '<div>Italiki :{creationdate}</div>',
                            '<div>Muri make :{detail}</div>',
                            ''
                        ]
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'top',
                title: 'Inyungu',
                items: [
                    {
                        xtype: 'button',
                        hidden: true,
                        id: 'backButton',
                        itemId: 'mybutton',
                        ui: 'back',
                        text: 'Back'
                    }
                ]
            }
        ],
        tabBar: {
            docked: 'bottom'
        },
        listeners: [
            {
                fn: 'onMylistSelect',
                event: 'select',
                delegate: '#mylist'
            },
            {
                fn: 'onBackButtonTap',
                event: 'tap',
                delegate: '#backButton'
            }
        ]
    },

    onMylistSelect: function(dataview, record, eOpts) {
        var currentTab = this.getActiveItem();
        var Details = currentTab.down('panel');
        Details.setRecord(record);
        currentTab.setActiveItem(Details);
        var backButton = Ext.getCmp('backButton');
        backButton.show();
    },

    onBackButtonTap: function(button, e, eOpts) {
        var currentTab = this.getActiveItem();
        currentTab.setActiveItem(0);
        button.hide();
    }

});